package inyecciondedependecias;

public class UsuarioServicio {

    private UsuarioRepositorio usuarioRepositorio;

    public UsuarioServicio(UsuarioRepositorio usuarioRepositorio) {
        this.usuarioRepositorio = usuarioRepositorio;
    }

    public void obtenerUsuario() {
        usuarioRepositorio.getUsuario();
    }


}

/*
La clase usuario servicio necesitara de UsuarioRepositorio para asi realizar consultas a la base de datos,
y delegar esa funcionalidad a otro tipo de clases

EN LOS CASO DE MALA PRACTICA, SE CREA UN ATRIBUTO COMO OBJETO DE LA CLASE QUE SE NECESITA
Y POR TANTO, PODEMOS UTILIZARLO EN CUALQUIER DE LOS METODOS DE LA CLASE
PERO ESTO ES UNA MALA PRACTICA, YA QUE ESTAMOS CREANDO UNA DEPENDENCIA DIRECTA DE LA CLASE USUARIO SERVICIO
Y EN CASO DE NECESITAR POR EJEMPLO, OTRO TIPO DE USUARIO, TENDRIA QUE CREARSE UN NUEVO ATRIBUTO DE OTRA CLASE, Y CAMBIAR LOS METODOS O AGREGAR NUEVOS METODOS

POR TANTO PASOS A SEGUIR:

HAY QUE DELEGAR LA CREACION DE LA CLASE A UN FACTOR EXTERNO, QUE SE ENCARGUE DE CREAR LA CLASE QUE NECESITAMOS
ES DECIR, EN LA CLASE SIMPLEMENTE INDICAMOS QUE NECESITAMOS UNAS DEPENDENCIAS EXCLISIVAS PARA TENER QUE CREAR LA CLASE
LAS CUALES DEBEN SER CASI SIEMPRE INTERFACES, PARA QUE SE PUEDAN IMPLEMENTAR EN CUALQUIER CLASE QUE NECESITEMOS

1. EN ESTE CASO, EL TIPO DE USUARIO GENERAL QUE SE NECESITA (USUARIO REPOSITORIO) SERA UNA INTERFAZ,
2. Y EN LA CLASE USUARIOSERVICIO, EN VEZ DE TENER UN ATRIBUTO YA INSTANCIADO,
3. SE DEFINIRA COMO ATRIBUTO LA INTERFAZ, Y SE CREARA UN CONSTRUCTOR CON UN PARAMETRO DE LA INTERFAZ UTILIZADA, ES DECIR UNA DEPENDENCIA

ES DECIR, SI SE NECESITA UNA INSTANCIA DE LA CLASE USUARIO SERVICIO, SE NECESITARA POR FUERZA UN USUARIO REPOSITORIO, QUE ES LA INTERFAZ
4. SUMADO A ELLO, UNA O DIFERENTES CLASES QUE SE NCESITEN, NECESARIAMENTE DEBERAN IMPLEMENTAR LA INTERFAZ CON SUS RESPECTIVOS METODOS
ESTO PARA QUE UsuarioRepositorio pueda ser instanciado en UsuarioServicio
5. EN EL MAIN, SE CREARA UNA INSTANCIA DE LA CLASE UsuarioRepositorio, ASIGNANDOLE CON NEW, LAS CLASES QUE IMPLEMENTEN UsuarioRepositorio
6. SE INICIARA UNA INSTANCIA DE UsuarioServicio, PASANDOLE COMO PARAMETRO LA INSTANCIA DE UsuarioRepositorio CREADA ANTERIORMENTE

EJEMPLO: UsuarioRepositorio usuarioRepositorio = new UsuarioMySqlRepositorio();
UsuarioServicio usuarioServicio = new UsuarioServicio(usuarioRepositorio);

AQUI SE ESTA CREANDO UNA INSTANCIA DE LA CLASE UsuarioMySqlRepositorio, Y COMO UsuarioMySqlRepositorio IMPLEMENTA UsuarioRepositorio
SE PUEDE CREAR UNA INSTANCIA DIRECTO DE UsuarioRepositorio, Y PASARLE COMO PARAMETRO LA INSTANCIA DE UsuarioMySqlRepositorio


 */