package adapter.adapter;

import adapter.model.Persona;

import java.io.InputStream;
import java.util.List;

public class FileAdapter {

    // ESTE ATRIBUTO PERMITE QUE PODREMOS RECIBIR CUALQUIER CLASE QUE IMPLEMENTE LA INTERFAZ
    private IInputFileReader inputFileReader;

    public FileAdapter(IInputFileReader inputFileReader) {
        this.inputFileReader = inputFileReader;
    }

    public List<Persona> readFile(InputStream inputStream) {
        return this.inputFileReader.readFile(inputStream);
    }
}

/*
EXPLICACION:

NOSOTROS CREAMOS UNA INTEFAZ IINPUTFILEREADER QUE CONTIENE UN METODO READ FILE, QUE LEERA CUALQUIER ARCHIVO
Y TENDREMOS UN ADAPTADOR QUE IMPLEMENTARA ESA INTERFAZ
Y POR EL INPUTSTREAM SE LE ENVIARA EL TIPO DE ARCHIVO, Y LO RECIBIREMOS CON EL METODO DE ESTA CLASE FILEADAPTER, Y CON ESE ADAPTAR, LEEREMOS EL ARCHIVO
Y DEPENDIENDO DEL ADAPTADOR QUE IMPLEMENTEMOS COMO ATRIBUTO, SE LEERA UNO U OTRO ARCHIVO.

LA CLASE FILEADAPTER RECIBE CUALQUIER ADAPTADOR QUE IMPLEMENTE LA INTERFAZ IINPUTFILEREADER, Y CON ESE ADAPTADOR, LEERA EL ARCHIVO
ACA LLAMAMOS A LA IMPLEMENTACION DEL ADAPTADOR POR EL METODO FILEADAPTER

 */